// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gossip_message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gossip struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	//Not sure about the validator key here
	//I guess the compressed message already has the vazlidator key
	ValidatorKey         []byte   `protobuf:"bytes,2,opt,name=validator_key,json=validatorKey,proto3" json:"validator_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gossip) Reset()         { *m = Gossip{} }
func (m *Gossip) String() string { return proto.CompactTextString(m) }
func (*Gossip) ProtoMessage()    {}
func (*Gossip) Descriptor() ([]byte, []int) {
	return fileDescriptor_288e7560062f96b3, []int{0}
}

func (m *Gossip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gossip.Unmarshal(m, b)
}
func (m *Gossip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gossip.Marshal(b, m, deterministic)
}
func (m *Gossip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gossip.Merge(m, src)
}
func (m *Gossip) XXX_Size() int {
	return xxx_messageInfo_Gossip.Size(m)
}
func (m *Gossip) XXX_DiscardUnknown() {
	xxx_messageInfo_Gossip.DiscardUnknown(m)
}

var xxx_messageInfo_Gossip proto.InternalMessageInfo

func (m *Gossip) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Gossip) GetValidatorKey() []byte {
	if m != nil {
		return m.ValidatorKey
	}
	return nil
}

type Control struct {
	Stream               bool     `protobuf:"varint,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Control) Reset()         { *m = Control{} }
func (m *Control) String() string { return proto.CompactTextString(m) }
func (*Control) ProtoMessage()    {}
func (*Control) Descriptor() ([]byte, []int) {
	return fileDescriptor_288e7560062f96b3, []int{1}
}

func (m *Control) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Control.Unmarshal(m, b)
}
func (m *Control) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Control.Marshal(b, m, deterministic)
}
func (m *Control) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Control.Merge(m, src)
}
func (m *Control) XXX_Size() int {
	return xxx_messageInfo_Control.Size(m)
}
func (m *Control) XXX_DiscardUnknown() {
	xxx_messageInfo_Control.DiscardUnknown(m)
}

var xxx_messageInfo_Control proto.InternalMessageInfo

func (m *Control) GetStream() bool {
	if m != nil {
		return m.Stream
	}
	return false
}

func init() {
	proto.RegisterType((*Gossip)(nil), "gossipmessage.Gossip")
	proto.RegisterType((*Control)(nil), "gossipmessage.Control")
}

func init() { proto.RegisterFile("gossip_message.proto", fileDescriptor_288e7560062f96b3) }

var fileDescriptor_288e7560062f96b3 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcf, 0x2f, 0x2e,
	0xce, 0x2c, 0x88, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x85, 0x88, 0x42, 0x05, 0x95, 0xdc, 0xb9, 0xd8, 0xdc, 0xc1, 0x02, 0x42, 0x12, 0x5c,
	0xec, 0x50, 0x41, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x18, 0x57, 0x48, 0x99, 0x8b, 0xb7,
	0x2c, 0x31, 0x27, 0x33, 0x25, 0xb1, 0x24, 0xbf, 0x28, 0x3e, 0x3b, 0xb5, 0x52, 0x82, 0x09, 0x2c,
	0xcf, 0x03, 0x17, 0xf4, 0x4e, 0xad, 0x54, 0x52, 0xe4, 0x62, 0x77, 0xce, 0xcf, 0x2b, 0x29, 0xca,
	0xcf, 0x11, 0x12, 0xe3, 0x62, 0x2b, 0x2e, 0x29, 0x4a, 0x4d, 0xcc, 0x05, 0x1b, 0xc4, 0x11, 0x04,
	0xe5, 0x19, 0x75, 0x31, 0x72, 0xf1, 0x42, 0x2c, 0xf3, 0x85, 0x9a, 0x6c, 0xcd, 0xc5, 0x51, 0x92,
	0xef, 0x93, 0x99, 0x14, 0x60, 0x14, 0x20, 0x24, 0xaa, 0x87, 0xe2, 0x32, 0x3d, 0x88, 0x4a, 0x29,
	0x31, 0x34, 0x61, 0xa8, 0x25, 0x4a, 0x0c, 0x42, 0x36, 0x5c, 0x9c, 0x25, 0xf9, 0x41, 0x99, 0x05,
	0x05, 0x39, 0xa9, 0x29, 0x24, 0xeb, 0x76, 0xd2, 0x8a, 0xd2, 0x48, 0xcf, 0x2c, 0xc9, 0x28, 0x4d,
	0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x77, 0xcb, 0x49, 0x2c, 0x0b, 0x4e, 0xce, 0x48, 0xcd, 0x4c, 0x29,
	0xd1, 0x87, 0xe8, 0x70, 0xcf, 0x0f, 0xce, 0x2b, 0xd1, 0x07, 0x87, 0x59, 0x12, 0x1b, 0x98, 0x32,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x79, 0xcf, 0x86, 0x02, 0x52, 0x01, 0x00, 0x00,
}
